services:
  prometheus:
    image: prom/prometheus:latest
    container_name: monitoring-prometheus
    networks:
      - shared
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus

  node-exporter:
    image: prom/node-exporter:latest
    container_name: monitoring-node-exporter
    networks:
      - shared
    pid: "host"
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --collector.filesystem.ignored-fs-types=^sysfs|^proc|^devtmpfs|^tmpfs|^overlay|^squashfs|^autofs|^cgroup$

  grafana:
    image: grafana/grafana:latest
    container_name: monitoring-grafana
    networks:
      - shared
    user: "472" # grafana user id (avoid permission issues)
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_ROOT_URL=https://grafana.thiagomvas.dev
      - GF_SERVER_SERVE_FROM_SUB_PATH=false
      - GF_ALLOW_EMBEDDING=true
      - GF_PROXY_TRUSTED_IPS=0.0.0.0/0
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - grafana_data:/var/lib/grafana

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: monitoring-cadvisor
    networks:
      - shared
    restart: unless-stopped
    privileged: true
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev:/dev:ro
      - /dev/mapper:/dev/mapper:ro   # optional, harmless if not present
    command: ["--housekeeping_interval=15s"]


volumes:
  prometheus_data:
  grafana_data:

networks:
  shared:
    external: true
