services:
  scripts-server:
    image: nginx:alpine
    container_name: scripts-server
    volumes:
      - ./scripts:/usr/share/nginx/html:ro
    networks:
      - shared
    restart: unless-stopped

networks:
  shared:
    external: true
