services:
  scripts-server:
    image: nginx:alpine
    container_name: scripts-server
    volumes:
      - ./scripts:/usr/share/nginx/html:ro
    networks:
      - shared
    restart: unless-stopped
    ports:
    - "${HOST_IP}:8888:80"

networks:
  shared:
    external: true
