emulatorjs:
  cache_limit: null
  controls: {}
  debug: false
  settings: {}
exclude:
  platforms: []
  roms:
    multi_file:
      names: []
      parts:
        extensions: []
        names: []
    single_file:
      extensions: []
      names:
      - Pokemon - FireRed Version [Subset - Professor Oak Challenge].bps
filesystem:
  firmware_folder: bios
  roms_folder: roms
scan:
  priority:
    artwork:
    - igdb
    - moby
    - ss
    - ra
    - launchbox
    - gamelist
    - hasheous
    - tgdb
    - flashpoint
    - hltb
    language:
    - en
    - fr
    metadata:
    - igdb
    - moby
    - ss
    - ra
    - launchbox
    - gamelist
    - hasheous
    - tgdb
    - flashpoint
    - hltb
    region:
    - us
    - wor
    - ss
    - eu
    - jp
system:
  platforms: {}
  versions: {}
