version: "3.9"
services:
  main:
    image: b3log/siyuan
    command: ['--workspace=/siyuan/workspace/', '--accessAuthCode=${AuthCode}']
    ports:
      - "${HOST_IP}:6806:6806"
    volumes:
      - ./siyuan-data:/siyuan
      - ./siyuan-data/workspace:/siyuan/workspace
    restart: unless-stopped
    environment:
      - TZ=America/Sao_Paulo

