services:
  glance:
    container_name: glance
    image: glanceapp/glance
    restart: unless-stopped
    volumes:
      - ./config:/app/config
      - ./assets:/app/assets
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    env_file: .env
    networks:
      - shared
    ports:
      - "${HOST_IP}:10000:8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.glance.rule=Host(`glance.thiagomvas.dev`)"
      - "traefik.http.routers.glance.entrypoints=websecure"
      - "traefik.http.services.glance.loadbalancer.server.port=8080"
      - "traefik.http.routers.glance.tls=true"

networks:
  shared:
    external: true
