global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['monitoring-prometheus:9090']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['monitoring-node-exporter:9100']

  - job_name: 'cadvisor'
    metrics_path: /metrics
    static_configs:
      - targets: ['monitoring-cadvisor:8080']

