global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['grafana-system-monitor-template-prometheus-1:9090']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['grafana-system-monitor-template-node-exporter-1:9100']

  - job_name: 'cadvisor'
    metrics_path: /metrics
    static_configs:
      - targets: ['grafana-system-monitor-template-cadvisor-1:8080']

