networks:
  shared:
    external: true

services:
  lidatube:
    image: thewicklowwolf/lidatube:latest
    container_name: media-lidatube
    user: "1000:1000"  
    volumes:
      - ../../services/media/music:/lidatube/downloads
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "${HOST_IP}:5000:5000"
    networks:
      - shared
    restart: unless-stopped

