networks:
  shared:
    external: true

services:
  lidatube:
    image: thewicklowwolf/lidatube:latest
    container_name: media-lidatube
    volumes:
      - ../../services/media/music:/lidatube/downloads
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "${HOST_IP}:5000:5000"
    networks:
      - shared
    restart: unless-stopped    
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lidatube.rule=Host(`lidatube.thiagomvas.dev`)"
      - "traefik.http.routers.lidatube.entrypoints=websecure"
      - "traefik.http.services.lidatube.loadbalancer.server.port=5000"
      - "traefik.http.routers.lidatube.tls=true"

